### ISSUE TITLE
Issues running Steam on Gentoo

### ISSUE THREAD

**Issue by JeffLabonte** [Witko/nvidia-xrun#84]
## Description

I am unable to run steam while using nvidia-xrun with openbox on Gentoo. However `glxinfo` returns the right GPU, I can run `glxgears` ,and I am able to play some games, i.e `albion-online`.

I am able to run steam when I use primusrun and also run games without any issues besides performance

## Issue encountered

Once I execute the `steam` command, I am having a `unable to load swrast.so drivers` and then a pop up menu that says `glXChooseVisual failed`.

## Additional infos

[cat /etc/X11/nvidia-xorg.conf](https://paste.pound-python.org/show/e9jHDEEKpQr6XAHzqigL/)
[find /usr/ -name "*nvidia"](https://paste.pound-python.org/show/IstX8mvsbIZpuOHcX4ts/)
[find /usr/ -name "*xorg"](https://paste.pound-python.org/show/aMIMUWLwJtijQBO1N5Sg/)

**Comment by JeffLabonte** [comment]
I found the solution, I need to add `sudo eselect set 1` when I start nvidia-xrun and then `sudo eselect set 2` once I am done!

**Comment by waltercool** [comment]
@JeffLabonte I personally fixed this issue doing this step:

At start, create a file called /etc/ld.conf.d/99-nvidia.conf with:
`/usr/lib/opengl/nvidia/lib
/usr/lib64/opengl/nvidia/lib`

Then run env-update, and should work fine.

When everything is done, just remove that file.

To make a quick context, with this we are overriding Nvidia's libGL.so at ld.so, used by Steam.

**Comment by asamsulfat** [comment]
@waltercool I have this problem too in Arch linux,
I realize there is no eselect in arch (only gentoo)

So I want to ask about your solution walter,
I don't have ld.conf.d directory, should I create it?
how to do env-update?

but I can open steam fine if I open it without nvidia-xrun (with intel)

**Comment by waltercool** [comment]
@asamsulfat It seems for Arch should be just adding the file into `/etc/ld.so.conf.d/`, then remove `ld.so.cache` and run `ldconfig` to regenerate it.

At least I done those steps into my raspberry pi (which uses Arch), but those steps may mean nothing:
- moved `ld.so.cache` as `ld.so.cache.backup`
- run `ldconfig`
- `diff ld.so.cache ld.so.cache.backup`
- Observe they are the same

Can you try some of those steps? Also observe if `/etc/ld.so.conf` has this line at start `include ld.so.conf.d/*.conf`

Steps to check if those works, could it be:
- Create the file as above 99-nvidia.conf
- Run same steps as I done above
- Observe if diff returns a different result.

In case you obtain diff of ld.so.cache with ld.so.cache.backup, I would Google a bit, and rollback. Because my main machine uses Gentoo, any advice from myself may break your system.

PD: eselect is Gentoo's architectural tool, just like env-update.

**Comment by LumKitty** [comment]
Having the same issue, only the eselect opengl solution is working for me.

I'm a little uncomfortable with it though. I'm running nvidia-xrun on a separate VT, and can switch between nvidia and intel/kde sessions with ctrl+alt+f1/f7, so if I were to run something else while my gaming session is going on in the background, isn't there a risk of it trying to run on nVidia and failing?

Is there a more elegant way to make Steam use the correct libraries?

**Comment by Witko** [comment]
This is quite weird,
in the script(nvidia-xinitrc) there is a hack for library path:
```
export LD_LIBRARY_PATH=/usr/lib64/nvidia/:/usr/lib32/nvidia:/usr/lib:${LD_LIBRARY_PATH}
```
If your paths differ then maybe you should change it. There is a support for custom xinitrc configs in
```
/etc/X11/xinit/nvidia-xinitrc.d/
```
directory or you could use the
```
userxinitrc=$HOME/.nvidia-xinitrc
```
Hope it helps!
